### ISSUE TITLE
Retrieve best candidate history 

### ISSUE THREAD

**Issue by agrayver** [beniz/libcmaes#104]
I would like to plot a histogram for a variable based on best candidates. Is it possible to retrieve best candidate history from CMASolutions? I see there is a member called _best_candidates_hist, but it seems there is no method to get it.

**Comment by beniz** [comment]
There's no accessor yet to _best_candidates_hist, and there may not be because it is a size-limited (i.e. incomplete) internal history that is primarily used by the stopping criteria.

There are at least two good ways to capture the history of best candidates:
- to customize a progress function and capture the best candidates from the current CMASolutions object there: since the progress function is a lambda, it should be possible to not use a global variable for storage, as needed;
- to expose the inner loop, see https://github.com/beniz/libcmaes/wiki/Defining-a-custom-algorithm-based-on-libcmaes-primitives and the relevant file in the repo, https://github.com/beniz/libcmaes/blob/master/examples/sample-code-ask-tell.cc.
In this case, the CMASolutions object is ready for inspection after 
    ```
   optim.tell();
   ```
has finished, on every time-step.

**Comment by agrayver** [comment]
Second strategy worked very well. Thank you.
