### ISSUE TITLE
avoiding eigenvalue calculations in active covariance update?

### ISSUE THREAD

**Issue by ssno** [beniz/libcmaes#144]
i am currently trying to parallelize "Active-CMA-ES" code to run on gpu.
in `acovarianceupdate.cc` calculation of  `cminusmin`  requires calculation of maximum eigenvalue .which is an iterative algorithm  and  so possible hit to performance . and as `cminusmin` is only used to provide upper bound for `cminus`. i was wondering is there any other way (any formula like we have for default `lambda` value) to calculate upper bound of `cminus` or is it okay to simply not using upper bound,will it make algorithm unstable?

**Comment by beniz** [comment]
FYI,if you haven't yet looked at it already, the publication the code is based on is https://hal.inria.fr/hal-00545728v1/document

I guess that getting a simpler approximate upper bound could do, but I wouldn't rely on this hunch, better wait for @nikohansen to comment on this.

**Comment by nikohansen** [comment]
Indeed, we can compute a bound in a simpler way. You can find the computations [here (submitted to `arXiv`)](https://www.lri.fr/~hansen/tutorial-new.pdf). In short, let `cminus=cmu` and `w-` the sum of the absolute values of negative weights. Then we can compute the bound on `w-` as (see Eq. (60))
```
w- < (1 - c1 - cmu) / cmu / dimension
```
This guaranties positive definiteness, **if** the squared Mahalanobis lengths of the update vectors with negative weights is normalized to `dimension` (see Eq. (46) and (47) in Fig. 6).

**Comment by ssno** [comment]
thanks for reply , i have read both papers ,and i am confused is w-  new terminology for cminus ? .
could you elaborate a bit?

**Comment by nikohansen** [comment]
> is `w-=cminus*alpha_old_minus/cmu` ? (from eq. (59) of arxiv paper)

this doesn't look correct, as it should not be zero if alpha_old_minus is zero. 

> and hence upper bound of cminus is w-bound*cmu/alpha_old? 

again, `alpha_old` is between zero and one, so this doesn't look right to me. In any case, the computed bound is for `alpha_old=1`, which is not considered as parameter anymore in the new formulation. 

For any value of `alpha_cov`, the simple bound to apply [here](https://hal.inria.fr/hal-00545728v1), where `w-=1` would be `c- < (1 - c1 - cmu) / D`, again using `D` instead of `||C^-1/2...||` in the nominator of (7). 

In general, the bound reads `w- c- < (1 - c1 - cmu) / D`, while the first paper considers `w-=1`, the second paper considers `c-=cmu`, both w.l.o.g. 

> or its equal to w-bounds `(1 - c1 - cmu) / cmu / dimension` .as arxiv paper is about plain(non-active)covarianceupdate it doesn't have cminus variable. 

you lost me.

**Comment by ssno** [comment]
thanks,now i get it now.
