### ISSUE TITLE
use_cholesky

### ISSUE THREAD

**Issue by micaelli** [beniz/libcmaes#165]
hello,
I am using libcmaes for biped locomotion (quite as Igor Mordatch 2010 work). This algo works quite well, but we have still time to save. Main part of computing time comes from covariance matrix decomposition, and we tried to use cholesky decomposition (putting use_cholesky = true). Unfortunately, somewhere in the code eigenvalues and eigenvectors are requested, and the program crashes. Eigen- values and vectors are they really needed? at first look to p.2 of [1], it seems that no, but I am not an expert... Is there a way to make work such a choice?

Thanks in advance for your help

[1]Nikolaus Hansen, Raymond Ros. Benchmarking a Weighted Negative Covariance Matrix Update on the BBOB-2010 Noiseless Testbed. Genetic And Evolutionary Computation Conference, Jul 2010, Portland, United States.

**Comment by nikohansen** [comment]
In order to compute the evolution path for the step-size update in the exact way as proposed in the original algorithm, eigenvalues and -vectors are needed. However there are variants which most of the time perform similar without to compute the eigendecomposition.

An alternative to save time is to apply the eigendecomposition less often, that is, not every iteration or every `n/10`-th iteration but only every `n`-th or even `3n`-th iteration. I am not aware of the default in `libcmaes`. If it is around `n/10`, as I would expect, going to `3n` saves a factor of 30, which is roughly the factor between Cholesky- and eigen-decomposition.

**Comment by micaelli** [comment]
@nikohansen many thanks for your quick answer, we'll test quickly the second solution. However, we are still interested in the first one; 

@nikohansen and @beniz : do you have any advice or guide in order to modifiy libcmaes in order to get rid of using covariance matrix eigen- vectors ans -values?

**Comment by micaelli** [comment]
In order to test first proposition of @nikohansen , we inserted in cmaparameters.cc : initialize_parameters():
 _lazy_update = true;
 _lazy_value = m; 
Is it the right way to proceed?

with m>3, the algorithm does not converge anymore. In our application: n = 20.

**Comment by nikohansen** [comment]
> with m>3, the algorithm does not converge anymore

That means the lazy update does not do what I would expect it to do. Providing plots to understand what _does not converge_ precisely means might help to find the reasons.

**Comment by beniz** [comment]
> we inserted in cmaparameters.cc

The lazy update value is set automatically if your program calls on `set_lazy_update(bool)`, see https://github.com/beniz/libcmaes/blob/master/tests/test-functions.cc#L526

**Comment by micaelli** [comment]
@nikohansen  and @beniz 
About "use_cholesky", I understood that choosing Cholesky decomposition was not an option in libcmaes, then the title of the issue is not appropriate, and if you agree, I will close it and open another one with a more appropriate title dealing with covariance matrix eigenvector decomposition.
